# Generated by Django 4.1.4 on 2023-02-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo_app', '0003_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
